# BUTTON ID'S
BUTTON_SQUARE = 0
BUTTON_CIRCLE = 2
BUTTON_CROSS = 1
BUTTON_TRIANGLE = 3

BUTTON_JOY_PAD_UP = 10
BUTTON_JOY_PAD_DOWN = 10
BUTTON_JOY_PAD_LEFT = 10
BUTTON_JOY_PAD_RIGHT = 12

BUTTON_L1 = 4
BUTTON_L2 = 6
BUTTON_R1 = 5
BUTTON_R2 = 7

BUTTON_START = 3
BUTTON_SELECT = 0
BUTTON_PS = 16

BUTTON_JOYSTICK_L = 1
BUTTON_JOYSTICK_R = 2

# AXIS ID'S
AXIS_SQUARE = 19
AXIS_CIRCLE = 17
AXIS_X = 18
AXIS_TRIANGLE = 16

AXIS_JOY_PAD_UP = 8
AXIS_JOY_PAD_DOWN = 10
AXIS_JOY_PAD_LEFT = None  # TODO:  Verify this is no axis
AXIS_JOY_PAD_RIGHT = 9

AXIS_JOYSTICK_L_HOR = 0
AXIS_JOYSTICK_L_VER = 1

AXIS_JOYSTICK_R_HOR = 2
AXIS_JOYSTICK_R_VER = 3

AXIS_L1 = 14
AXIS_L2 = 12

AXIS_R1 = 15
AXIS_R2 = 13

AXIS_SIX_AXIS = 25

